// Shared, product-aligned content for the public prototype.
// Numbers shown here are service ranges or process targets from the product plan,
// not fabricated platform performance data.

export const serviceSkus = [
  {
    id: 'diagnosis',
    name: '问题诊断',
    fit: '问题已经发生，但根因和下一步还不清楚',
    deliverable: '会前问题单、60-90 分钟诊断、行动纪要',
    duration: '1-3 天',
  },
  {
    id: 'micro-task',
    name: '微任务',
    fit: '范围清楚，需要一份可直接使用的成果',
    deliverable: '调研、诊断、文案、名单或方案等明确交付物',
    duration: '3-10 天',
  },
  {
    id: 'collaboration',
    name: '协作验证',
    fit: '准备长期合作或招聘，希望先观察真实协作',
    deliverable: '2-4 周真实项目、里程碑、周报与复盘',
    duration: '2-4 周',
  },
];

// Reusable enterprise-side problem briefs. These are examples, not live customer cases.
// Every item is written in a form that can be turned into a scoped, paid task.
export const enterpriseDemandCatalog = [
  {
    id: 'tiktok-organic-traffic-drop',
    title: 'TikTok 自然流量持续下滑',
    category: '内容增长',
    priority: '首发重点',
    markets: ['印尼', '东南亚'],
    stage: '增长期',
    summary: '账号仍在稳定更新，但自然播放、完播或互动连续下降，常规申诉和换题材没有形成稳定改善。',
    impact: '新品发布节奏、自然获客占比和团队判断效率受到影响。',
    example: '我们面向印尼的 TikTok 官方账号连续三周自然流量下降，已经影响新品发布。团队做过申诉和内容调整，但还不清楚是账号健康、内容结构还是分发策略的问题。',
    goal: '区分账号、内容、受众和运营节奏中的主要问题，明确先验证什么、暂时不做什么。',
    deliverables: ['账号审计', '根因假设与证据', '14 天行动清单'],
    acceptance: '关键判断能对应后台数据或样本；行动项有优先级、负责人和复查时间。',
    inputs: '近 30-90 天后台数据、内容样本、发布时间和已尝试动作。',
    boundary: '不承诺恢复流量，不代替平台申诉或违规处置。',
    service: '专家快诊 / 标准微任务',
    duration: '1-7 天',
    budget: '¥999-12,000',
    capabilityIds: ['tiktok-account-diagnosis', 'growth-experiment-design'],
    keywords: ['tiktok', '限流', '播放量', '完播', '互动', '账号', '自然流量'],
  },
  {
    id: 'localized-content-system',
    title: '东南亚内容本地化体系重做',
    category: '内容增长',
    priority: '首发重点',
    markets: ['印尼', '马来西亚', '泰国'],
    stage: '验证期 / 增长期',
    summary: '总部内容可以翻译，但当地用户不互动；团队缺少受众语境、内容支柱和本地审核标准。',
    impact: '品牌表达难以建立当地认知，内容制作成本增加，测试结果也难以复用。',
    example: '现有内容大多从中文直接翻译，语法没有问题，但评论和转发很少。我们希望知道哪些表达不符合当地语境，并建立一套可以持续使用的内容框架。',
    goal: '把品牌信息转为当地用户能理解、愿意互动的主题、表达和制作规则。',
    deliverables: ['受众语境地图', '内容支柱', '本地化样稿与审核表'],
    acceptance: '每个主题说明目标人群、使用场景和禁用表达；样稿可直接进入小规模测试。',
    inputs: '品牌定位、目标人群、历史内容、当地反馈和合规限制。',
    boundary: '不把单次翻译等同于本地化，不承诺单条内容的传播结果。',
    service: '标准微任务',
    duration: '5-10 天',
    budget: '¥6,000-20,000',
    capabilityIds: ['localized-content-strategy', 'overseas-user-research'],
    keywords: ['本地化', '翻译', '文案', '内容策略', '语境', '品牌表达'],
  },
  {
    id: 'creator-partnership-reset',
    title: '达人名单很多，但合作质量不稳定',
    category: '达人合作',
    priority: '首发重点',
    markets: ['印尼', '泰国', '马来西亚'],
    stage: '增长期',
    summary: '团队积累了大量达人名单，但筛选依赖粉丝量，报价、内容质量、品牌风险和复盘口径不统一。',
    impact: '沟通与投放预算被低质量候选消耗，品牌风险和复投判断缺少依据。',
    example: '我们每月都会联系达人，但回复率、交付质量和复投判断都不稳定。希望先建立筛选标准，再形成一批适合当前产品的候选人。',
    goal: '建立从筛选、触达、brief 到复盘的可重复合作机制。',
    deliverables: ['筛选评分卡', '候选名单', '合作 brief 与复盘模板'],
    acceptance: '候选人注明选择理由、风险和建议合作方式；名单来源与联系状态可追溯。',
    inputs: '产品信息、目标受众、预算、历史合作记录和品牌风险要求。',
    boundary: '名单不等于合作承诺；实际档期、报价和内容授权需单独确认。',
    service: '标准微任务',
    duration: '5-10 天',
    budget: '¥5,000-18,000',
    capabilityIds: ['creator-partnership'],
    keywords: ['达人', 'kol', '网红', '名单', 'brief', '报价', '投放'],
  },
  {
    id: 'new-market-entry-evidence',
    title: '进入新市场前，先补齐决策证据',
    category: '市场进入',
    priority: '首发重点',
    markets: ['新加坡', '印尼', '泰国', '东南亚'],
    stage: '验证期',
    summary: '管理层想进入一个国家，但竞争、渠道、目标客群和验证顺序仍停留在零散信息层面。',
    impact: '市场优先级、预算安排和进入时点无法形成一致决策。',
    example: '我们正在比较印尼和泰国，已经收集过宏观数据，但还不能回答先服务谁、从哪个渠道测试、什么信号代表值得继续投入。',
    goal: '形成可用于进入决策的竞品、用户、渠道和验证假设。',
    deliverables: ['竞品与替代方案图谱', '渠道假设', '进入验证清单'],
    acceptance: '结论注明证据来源与不确定性；每个验证动作都有成本、信号和停止条件。',
    inputs: '产品能力、目标客户、可投入资源、已有研究和管理层关键问题。',
    boundary: '不是完整国家战略，也不替代法律、税务或牌照专业意见。',
    service: '专家快诊 / 标准微任务',
    duration: '5-15 天',
    budget: '¥8,000-30,000',
    capabilityIds: ['market-entry-mapping', 'overseas-user-research'],
    keywords: ['市场进入', '国家选择', '竞品', '渠道', '验证', '进入策略'],
  },
  {
    id: 'user-research-sprint',
    title: '两周内完成一轮海外用户验证',
    category: '用户研究',
    priority: '首发重点',
    markets: ['新加坡', '印尼', '泰国'],
    stage: '验证期 / 增长期',
    summary: '团队对用户需求有假设，但缺少当地用户的一手证据，产品、定价或内容决策长期依赖内部讨论。',
    impact: '产品、定价和运营决策反复讨论，错过低成本验证窗口。',
    example: '我们想验证目标用户为什么试用后不继续使用，需要在两周内完成访谈并得到能直接影响产品和运营的结论。',
    goal: '用小样本、结构化访谈快速确认关键假设、分歧和下一步验证方向。',
    deliverables: ['研究问题与招募标准', '脱敏访谈纪要', '洞察与行动建议'],
    acceptance: '结论能回到原始证据；区分用户原话、研究判断和团队假设。',
    inputs: '研究目标、目标用户定义、现有数据、招募渠道和可执行决策。',
    boundary: '小样本研究不代表总体比例，不输出没有证据的市场规模结论。',
    service: '标准微任务',
    duration: '7-15 天',
    budget: '¥8,000-28,000',
    capabilityIds: ['overseas-user-research'],
    keywords: ['用户研究', '访谈', '需求验证', '留存', '用户洞察', '定价'],
  },
  {
    id: 'ecommerce-conversion-audit',
    title: 'Shopee / Lazada 店铺转化诊断',
    category: '电商运营',
    priority: '可匹配',
    markets: ['印尼', '泰国', '东南亚'],
    stage: '增长期',
    summary: '店铺有访问和活动投入，但商品结构、详情页、价格、评价或履约环节的主要损失点不清楚。',
    impact: '流量与活动投入无法稳定转化为订单，团队也难以确定优化优先级。',
    example: '活动期间流量明显增加，但订单增长有限。团队希望区分是选品、详情页、价格、评价还是履约问题，并确定先改哪一项。',
    goal: '找到从访问到下单链路中的主要摩擦，并形成按影响和实施难度排序的优化计划。',
    deliverables: ['店铺漏斗审计', '商品与页面问题清单', '优先级优化计划'],
    acceptance: '问题能对应页面或后台证据；建议注明预计影响方向和验证方式。',
    inputs: '店铺后台、商品页、活动记录、评价样本和履约数据。',
    boundary: '不承诺 GMV 或转化率结果，不代替平台规则与合规审查。',
    service: '专家快诊 / 标准微任务',
    duration: '3-10 天',
    budget: '¥4,000-18,000',
    capabilityIds: ['ecommerce-store-audit', 'growth-experiment-design'],
    keywords: ['shopee', 'lazada', '店铺', '转化', '详情页', '选品', 'gmv'],
  },
  {
    id: 'growth-experiment-backlog',
    title: '把增长目标变成可验证实验',
    category: '增长策略',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    stage: '增长期',
    summary: '团队有很多增长想法，但缺少统一假设、指标口径、优先级和停止条件，执行后也难以复盘。',
    impact: '增长资源分散在零散动作中，实验结果不能支持下一轮投入决策。',
    example: '我们想提高首月留存，但内容、激励、产品引导和渠道质量都可能影响结果。希望先形成一组可以在两周内验证的实验。',
    goal: '把目标拆成关键障碍、可测试假设和有明确决策门槛的实验队列。',
    deliverables: ['增长问题树', '实验优先级', '两周验证计划'],
    acceptance: '每个实验包含假设、人群、动作、指标、周期和继续或停止条件。',
    inputs: '目标指标、历史数据、可用渠道、产品限制和团队资源。',
    boundary: '不使用无法归因的虚假增长，不承诺单个实验一定成功。',
    service: '专家快诊 / 付费试用',
    duration: '3 天-4 周',
    budget: '¥3,000-35,000',
    capabilityIds: ['growth-experiment-design', 'analytics-measurement'],
    keywords: ['增长', '实验', '留存', '转化', '指标', 'ab测试', '归因'],
  },
  {
    id: 'ai-service-workflow',
    title: '搭建可控的海外客服 AI 工作流',
    category: 'AI 提效',
    priority: '第二阶段',
    markets: ['多市场', '东南亚'],
    stage: '规模化',
    summary: '客服问题重复、知识分散、语言多，但团队担心自动回复出错、升级不及时或敏感信息泄露。',
    impact: '客服成本和响应时间持续增加，同时存在错误回复与敏感信息风险。',
    example: '我们希望先用 AI 处理高频问题，但需要明确哪些可以自动回复、哪些必须转人工，以及如何更新知识和检查错误。',
    goal: '从高频问题、知识来源和风险等级出发，设计有人负责、可复核的客服提效流程。',
    deliverables: ['问题分类与知识结构', '工作流原型', '人工升级与抽检规则'],
    acceptance: '每类问题有来源、回复边界和升级责任人；原型能用测试集复查。',
    inputs: '历史会话、FAQ、产品政策、禁答事项、语言和客服组织方式。',
    boundary: '不让模型独立处理退款、法律承诺、安全事故或其他高风险决策。',
    service: '标准微任务 / 付费试用',
    duration: '7-20 天',
    budget: '¥10,000-45,000',
    capabilityIds: ['ai-customer-service', 'cross-border-project-delivery'],
    keywords: ['ai', '客服', '知识库', '自动化', '人工升级', '工作流'],
  },
  {
    id: 'channel-partner-map',
    title: '建立当地渠道与合作伙伴图谱',
    category: '渠道拓展',
    priority: '可匹配',
    markets: ['印尼', '新加坡', '马来西亚'],
    stage: '验证期 / 增长期',
    summary: '团队知道需要当地渠道，但潜在伙伴类型、筛选标准、合作价值和验证路径没有形成系统。',
    impact: '区域拓展依赖临时介绍，伙伴验证周期长且沟通投入不可控。',
    example: '我们收到过代理商和服务商介绍，但无法比较谁真的覆盖目标客户，也不清楚第一次沟通应该验证什么。',
    goal: '明确渠道角色、候选优先级和首轮接触的验证问题。',
    deliverables: ['渠道生态图', '候选伙伴清单', '筛选与首轮沟通模板'],
    acceptance: '候选信息注明来源、匹配理由和待核验事项；不把公开名单包装成已合作资源。',
    inputs: '产品类型、目标客户、合作模式、区域限制和已有联系人。',
    boundary: '不承诺渠道签约，不替代尽调、合同或合规审查。',
    service: '标准微任务',
    duration: '7-15 天',
    budget: '¥8,000-25,000',
    capabilityIds: ['channel-partner-development', 'market-entry-mapping'],
    keywords: ['渠道', '代理商', '合作伙伴', '分销', '生态', '名单'],
  },
  {
    id: 'b2b-lead-pipeline',
    title: '从零搭建海外 B2B 线索流程',
    category: '渠道拓展',
    priority: '可匹配',
    markets: ['新加坡', '东南亚', '多市场'],
    stage: '验证期 / 增长期',
    summary: '销售依赖个人关系或临时名单，目标客户、触达节奏、资格判断和跟进记录没有统一口径。',
    impact: '合格线索供给不稳定，销售时间被低意向账户消耗，收入预测缺少依据。',
    example: '我们有一批潜在客户名单，但回复很少，也不知道哪些线索值得继续投入。希望先做一个小范围的触达和资格验证流程。',
    goal: '把目标账户、价值主张、触达和资格判断组合成可复用的线索流程。',
    deliverables: ['目标账户标准', '触达脚本', '资格判断与跟进模板'],
    acceptance: '名单来源合规；每个触达版本有目标人群、假设和记录方式。',
    inputs: '产品价值、典型客户、历史成交、现有名单和销售资源。',
    boundary: '不采用垃圾邮件、虚假身份或未经授权的数据抓取。',
    service: '标准微任务 / 付费试用',
    duration: '7 天-4 周',
    budget: '¥8,000-40,000',
    capabilityIds: ['b2b-demand-generation', 'channel-partner-development'],
    keywords: ['b2b', '销售线索', '客户名单', '外呼', '邮件', 'linkedin', '获客'],
  },
  {
    id: 'retention-repurchase-diagnosis',
    title: '首购有增长，但复购和留存偏弱',
    category: '用户运营',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    stage: '增长期 / 规模化',
    summary: '获客投入增加，但不同渠道和人群的复购差异不清楚，触达内容、时间和优惠缺少分层。',
    impact: '获客回收周期被拉长，收入质量和用户长期价值难以改善。',
    example: '新客订单在增长，但第二次购买的人不多。团队希望先看清哪些用户有复购潜力，再设计一轮可验证的触达。',
    goal: '识别关键留存节点和用户分层，形成可执行的复购实验。',
    deliverables: ['用户分层与路径', '流失假设', '复购触达实验'],
    acceptance: '分层口径可复现；触达方案注明人群、时机、内容和退出规则。',
    inputs: '订单或行为数据、渠道来源、触达记录、产品周期和优惠限制。',
    boundary: '不滥用个人信息，不进行未经同意的高频骚扰式触达。',
    service: '专家快诊 / 标准微任务',
    duration: '5-15 天',
    budget: '¥6,000-25,000',
    capabilityIds: ['lifecycle-retention', 'analytics-measurement'],
    keywords: ['留存', '复购', 'crm', '用户分层', '流失', '生命周期'],
  },
  {
    id: 'regional-launch-delivery',
    title: '跨市场发布项目失去节奏',
    category: '项目交付',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    stage: '增长期 / 规模化',
    summary: '总部、当地团队、供应商和渠道同时参与，信息分散在聊天记录里，依赖、决策和验收人不清楚。',
    impact: '发布延期、重复返工和责任模糊增加，多个市场难以保持统一节奏。',
    example: '新品要在三个市场同步发布，但素材、翻译、渠道和审批进度各自管理。希望先建立一套能在本次发布中使用的协作机制。',
    goal: '把范围、依赖、里程碑和决策责任放到一个可追踪的交付框架中。',
    deliverables: ['发布工作分解', '依赖与风险清单', '里程碑和会议机制'],
    acceptance: '每项关键任务有负责人、截止时间和确认方式；风险有触发信号和升级路径。',
    inputs: '发布时间、参与方、当前计划、关键依赖、审批规则和沟通工具。',
    boundary: '不替代各方业务责任，不为未确认的外部依赖作保证。',
    service: '付费试用项目',
    duration: '2-4 周',
    budget: '¥15,000-50,000',
    capabilityIds: ['cross-border-project-delivery'],
    keywords: ['项目管理', '跨市场', '发布', '里程碑', '协作', '供应商'],
  },
];

export const capabilityCatalog = [
  {
    id: 'tiktok-account-diagnosis',
    name: 'TikTok 账号增长诊断',
    category: '内容增长',
    priority: '当前重点',
    markets: ['印尼', '东南亚'],
    description: '定位自然流量、账号健康、内容结构或投放协同中的具体问题。',
    tasks: ['账号健康与流量异常诊断', '内容样本与指标对照', '短周期调整优先级设计'],
    methods: '后台数据审计、内容分组、时间线对照、竞品样本和根因假设排序',
    deliverables: ['账号审计', '问题优先级', '14 天行动清单'],
    acceptance: '每个关键判断能对应数据或样本，行动项有负责人、复查时间和停止条件。',
    evidence: '同市场账号后台数据、诊断文档或合作方评价',
    boundary: '不能承诺解除平台限制或恢复特定流量。',
    service: '专家快诊 / 标准微任务',
    duration: '1-10 天',
    keywords: ['tiktok', '限流', '自然流量', '账号', '短视频', '播放量'],
  },
  {
    id: 'localized-content-strategy',
    name: '东南亚本地化内容策略',
    category: '内容增长',
    priority: '当前重点',
    markets: ['印尼', '马来西亚', '泰国'],
    description: '把品牌信息转成当地用户能理解、愿意互动的内容主题与表达。',
    tasks: ['受众语境与禁用表达梳理', '内容支柱和栏目设计', '本地化样稿与审核机制'],
    methods: '用户语境分析、当地内容采样、表达校准、样稿测试和本地团队复核',
    deliverables: ['受众洞察', '内容支柱', '本地化样稿'],
    acceptance: '主题、语气和样稿能对应目标人群与使用场景，并可进入小规模发布测试。',
    evidence: '已发布内容、互动数据、内容日历或本地团队反馈',
    boundary: '不把直译或单次润色包装成完整本地化能力。',
    service: '标准微任务',
    duration: '5-10 天',
    keywords: ['本地化', '内容', '文案', '语言', '社媒', '品牌'],
  },
  {
    id: 'overseas-user-research',
    name: '海外用户研究与访谈',
    category: '市场进入',
    priority: '当前重点',
    markets: ['新加坡', '印尼', '泰国'],
    description: '围绕进入判断、产品定位或增长障碍，获得可用于决策的一手用户证据。',
    tasks: ['研究问题与样本定义', '深度访谈与行为追问', '洞察归纳和决策建议'],
    methods: '研究设计、半结构化访谈、主题编码、反例检查和证据链整理',
    deliverables: ['访谈提纲', '访谈纪要', '洞察与建议'],
    acceptance: '结论可追溯到原始证据，明确区分用户原话、研究判断和待验证假设。',
    evidence: '研究方案、脱敏纪要、结论被采用的证明',
    boundary: '小样本研究不代表总体比例，不替代大规模定量研究。',
    service: '标准微任务',
    duration: '7-15 天',
    keywords: ['用户研究', '访谈', '市场进入', '用户偏好', '需求验证'],
  },
  {
    id: 'market-entry-mapping',
    name: '市场进入与竞品图谱',
    category: '市场进入',
    priority: '当前重点',
    markets: ['东南亚', '新加坡', '印尼'],
    description: '把模糊的“想进入一个国家”拆成市场、竞争、渠道和验证顺序。',
    tasks: ['竞品与替代方案扫描', '目标客群和渠道假设', '进入验证路径设计'],
    methods: '桌面研究、竞品拆解、渠道访谈、假设排序和停止条件设计',
    deliverables: ['竞品图谱', '渠道假设', '进入验证清单'],
    acceptance: '结论注明证据来源和不确定性，验证动作有成本、信号和继续条件。',
    evidence: '历史调研报告、渠道验证结果或项目复盘',
    boundary: '不替代法律、税务、牌照或正式投资决策意见。',
    service: '专家快诊 / 标准微任务',
    duration: '3-15 天',
    keywords: ['进入', '竞品', '市场', '渠道', '调研', '国家'],
  },
  {
    id: 'creator-partnership',
    name: '达人筛选与合作设计',
    category: '内容增长',
    priority: '可匹配',
    markets: ['印尼', '泰国', '马来西亚'],
    description: '根据目标人群、预算和品牌风险，建立达人筛选与合作执行方案。',
    tasks: ['达人筛选标准设计', '候选人调研与分层', '合作 brief 和复盘机制'],
    methods: '受众匹配、内容质量审计、互动真实性检查、报价对照和风险标记',
    deliverables: ['达人筛选标准', '候选名单', '合作与复盘模板'],
    acceptance: '候选名单注明来源、选择理由、风险和建议合作方式，信息可追溯。',
    evidence: '达人名单、合作数据、ROI 复盘或谈判记录',
    boundary: '候选名单不代表已确认档期、报价或合作意愿。',
    service: '标准微任务',
    duration: '5-10 天',
    keywords: ['达人', 'kol', '网红', '合作', '投放', 'roi'],
  },
  {
    id: 'ecommerce-store-audit',
    name: '东南亚电商店铺诊断',
    category: '电商运营',
    priority: '可匹配',
    markets: ['东南亚', '印尼', '泰国'],
    description: '检查商品结构、页面转化、活动节奏和运营动作，定位增长卡点。',
    tasks: ['店铺漏斗和商品结构审计', '详情页与评价摩擦识别', '活动与运营动作复盘'],
    methods: '后台数据拆解、商品分组、页面启发式审计、评价主题归纳和优先级排序',
    deliverables: ['店铺诊断', '问题清单', '优先级行动方案'],
    acceptance: '问题能对应页面或数据证据，建议包含影响方向、实施难度和验证方法。',
    evidence: '店铺后台、运营方案、GMV 或转化改善记录',
    boundary: '不承诺 GMV、排名或特定转化提升。',
    service: '专家快诊 / 标准微任务',
    duration: '3-10 天',
    keywords: ['shopee', 'lazada', '电商', '店铺', '转化', '选品'],
  },
  {
    id: 'ai-customer-service',
    name: '海外客服 AI 工作流',
    category: 'AI 提效',
    priority: '第二阶段',
    markets: ['多市场'],
    description: '从高频问题、知识来源和人工升级规则出发，设计可控的客服提效流程。',
    tasks: ['客服问题分类', '知识来源与更新责任设计', '自动回复和人工升级规则配置'],
    methods: '会话抽样、意图聚类、知识盘点、测试集评估和高风险问题隔离',
    deliverables: ['知识库结构', '工作流原型', '人工升级规则'],
    acceptance: '回复能追溯知识来源，高风险问题明确转人工，原型通过代表性测试集检查。',
    evidence: '已运行工作流、准确率、响应时长或人工节省记录',
    boundary: '不让模型独立处理退款、法律承诺或安全事故等高风险决定。',
    service: '标准微任务 / 付费试用',
    duration: '7-20 天',
    keywords: ['ai', '客服', '知识库', '自动化', '工作流', '效率'],
  },
  {
    id: 'growth-experiment-design',
    name: '海外增长实验设计',
    category: '增长策略',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    description: '把增长目标拆成可验证假设、实验动作、指标和停止条件。',
    tasks: ['增长障碍和假设地图', '实验优先级排序', '指标口径与复盘机制'],
    methods: '问题树、影响与成本评估、实验设计、数据口径校准和复盘归因',
    deliverables: ['实验地图', '指标口径', '两周验证计划'],
    acceptance: '每个实验包含人群、假设、动作、指标、周期和继续或停止条件。',
    evidence: '实验记录、数据看板、结果复盘或业务采纳证明',
    boundary: '不采用误导性增长手段，不把相关性包装成因果。',
    service: '专家快诊 / 付费试用',
    duration: '3 天-4 周',
    keywords: ['增长', '实验', '转化', '留存', '数据', '策略'],
  },
  {
    id: 'paid-media-funnel-audit',
    name: '海外付费投放漏斗诊断',
    category: '增长策略',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    description: '从受众、素材、落地页和转化链路出发，定位投放成本上升或线索质量不稳定的原因。',
    tasks: ['账户和受众结构审计', '素材与落地页信息一致性检查', '归因和转化路径复盘'],
    methods: '漏斗拆解、分组对照、素材审计、落地页启发式检查和归因口径校准',
    deliverables: ['投放漏斗诊断', '问题优先级', '素材与页面测试计划'],
    acceptance: '关键问题能对应数据或页面证据，测试计划包含人群、变量、指标和预算边界。',
    evidence: '广告后台、素材版本、落地页、转化数据和历史复盘',
    boundary: '不承诺 ROAS 或获客成本结果，不绕过平台广告政策。',
    service: '专家快诊 / 标准微任务',
    duration: '3-10 天',
    keywords: ['投放', '广告', 'facebook', 'meta', 'google', '落地页', 'roas', '获客成本'],
  },
  {
    id: 'channel-partner-development',
    name: '海外渠道与合作伙伴开发',
    category: '渠道拓展',
    priority: '可匹配',
    markets: ['印尼', '新加坡', '马来西亚', '东南亚'],
    description: '识别渠道角色、筛选潜在伙伴，并设计首轮接触和资格验证路径。',
    tasks: ['渠道生态与角色梳理', '候选伙伴调研', '首轮触达和资格判断'],
    methods: '生态映射、公开信息核验、相似客户反查、价值主张设计和访谈验证',
    deliverables: ['渠道生态图', '候选伙伴清单', '触达与筛选模板'],
    acceptance: '候选信息注明来源、匹配理由和待核验项，不把公开名单包装成现成关系。',
    evidence: '渠道项目记录、候选清单、沟通记录、签约或验证结果',
    boundary: '不承诺签约，不替代伙伴尽调、合同和合规审查。',
    service: '标准微任务 / 付费试用',
    duration: '7 天-4 周',
    keywords: ['渠道', '代理商', '分销', '合作伙伴', '生态', '签约', '本地资源'],
  },
  {
    id: 'b2b-demand-generation',
    name: '海外 B2B 线索与触达体系',
    category: '渠道拓展',
    priority: '可匹配',
    markets: ['新加坡', '东南亚', '多市场'],
    description: '把目标账户、价值主张、合规触达和资格判断组合成可复用的线索流程。',
    tasks: ['目标账户标准定义', '线索研究与分层', '触达脚本和跟进节奏设计'],
    methods: 'ICP 拆解、账户研究、信号分层、消息测试、资格标准和跟进记录',
    deliverables: ['目标账户清单', '多版本触达脚本', '资格与跟进模板'],
    acceptance: '名单来源合规，触达版本对应具体人群与假设，跟进状态可追踪。',
    evidence: '历史线索、触达数据、会议转化、销售反馈或成交复盘',
    boundary: '不进行垃圾邮件、虚假身份或未经授权的数据抓取。',
    service: '标准微任务 / 付费试用',
    duration: '7 天-4 周',
    keywords: ['b2b', '销售', '线索', 'linkedin', '邮件', '外贸', '客户名单', '获客'],
  },
  {
    id: 'lifecycle-retention',
    name: '海外用户生命周期与复购运营',
    category: '用户运营',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    description: '识别关键留存节点和用户分层，设计不过度打扰且可验证的复购与召回动作。',
    tasks: ['用户分层和关键路径分析', '流失信号识别', '复购或召回实验设计'],
    methods: '队列分析、行为分层、生命周期映射、触达策略和退出规则设计',
    deliverables: ['生命周期地图', '用户分层', '复购与召回实验'],
    acceptance: '分层口径可复现，触达方案注明人群、时机、内容、频率和退出条件。',
    evidence: '订单或行为数据、CRM 方案、触达记录、留存或复购复盘',
    boundary: '不滥用个人信息，不设计未经同意的骚扰式触达。',
    service: '专家快诊 / 标准微任务',
    duration: '5-15 天',
    keywords: ['留存', '复购', 'crm', '召回', '用户分层', '生命周期', '私域'],
  },
  {
    id: 'analytics-measurement',
    name: '海外业务指标与归因口径',
    category: '数据分析',
    priority: '可匹配',
    markets: ['多市场'],
    description: '把分散数据转成团队能共同使用的指标定义、分析框架和决策看板。',
    tasks: ['业务目标与指标树设计', '数据口径和来源核对', '分析框架与复盘模板搭建'],
    methods: '指标树、数据字典、漏斗与队列分析、异常检查和决策问题映射',
    deliverables: ['指标字典', '分析框架', '看板或复盘模板'],
    acceptance: '每个指标说明定义、来源、更新频率和负责人，避免同名不同口径。',
    evidence: '数据字典、查询逻辑、分析报告、看板和被采纳的业务决策',
    boundary: '不把不完整数据包装成确定结论，不绕过数据权限。',
    service: '标准微任务',
    duration: '5-15 天',
    keywords: ['数据', '指标', '看板', '归因', '漏斗', '留存', '分析', 'bi'],
  },
  {
    id: 'product-market-localization',
    name: '产品与价格本地化验证',
    category: '市场进入',
    priority: '可匹配',
    markets: ['印尼', '泰国', '马来西亚', '东南亚'],
    description: '验证产品组合、价格表达、支付习惯和使用门槛是否适合目标市场。',
    tasks: ['本地替代方案与价格带调研', '产品组合和价值表达校准', '小规模验证方案设计'],
    methods: '竞品采样、用户访谈、价格表达对照、渠道反馈和验证实验设计',
    deliverables: ['价格与替代方案图谱', '本地化假设', '验证计划'],
    acceptance: '假设能对应当地证据，明确哪些是事实、判断和仍需验证的问题。',
    evidence: '竞品采样、用户反馈、价格测试、渠道数据或上市复盘',
    boundary: '不替代财税、支付合规或正式定价决策。',
    service: '专家快诊 / 标准微任务',
    duration: '5-15 天',
    keywords: ['产品本地化', '定价', '价格', '支付', '套餐', '市场进入', '竞品'],
  },
  {
    id: 'cross-border-project-delivery',
    name: '跨市场项目交付与协作',
    category: '项目交付',
    priority: '可匹配',
    markets: ['东南亚', '多市场'],
    description: '协调总部、当地团队、供应商和渠道，建立范围、依赖、里程碑与风险升级机制。',
    tasks: ['项目范围和工作分解', '跨团队依赖与风险管理', '会议、决策和验收机制设计'],
    methods: '工作分解、RACI、风险登记、里程碑管理、决策日志和变更控制',
    deliverables: ['项目计划', '依赖与风险清单', '沟通和验收机制'],
    acceptance: '关键任务有负责人、截止时间和确认方式，变更与风险有明确升级路径。',
    evidence: '项目计划、会议纪要、交付记录、风险处理和合作方评价',
    boundary: '不替代业务方决策，不为未确认的外部依赖作保证。',
    service: '付费试用项目',
    duration: '2-4 周',
    keywords: ['项目管理', '交付', '跨市场', '供应商', '里程碑', '风险', '协作'],
  },
];

export const talentSkillTemplates = [
  {
    id: 'content-diagnosis',
    category: '内容增长',
    name: '海外内容与账号诊断',
    task: '识别账号、内容结构或增长链路中的主要问题',
    method: '内容审计、数据对照、竞品拆解与优先级判断',
    fit: '内容增长快诊、账号审计、行动方案',
    deliverables: ['账号审计', '根因假设', '调整优先级'],
    evidenceExamples: '后台数据、诊断文档、内容样本和行动被采纳的记录',
    boundary: '不能仅凭职位名称证明，也不能承诺恢复特定流量。',
    evidencePrompt: '补充后台数据、诊断文档或被采纳的行动记录',
    keywords: ['内容', 'tiktok', '账号', '流量', '短视频', '社媒', '运营'],
  },
  {
    id: 'localization',
    category: '本地化',
    name: '市场本地化与内容适配',
    task: '把产品、品牌或内容调整为当地用户可理解的表达',
    method: '用户语境分析、本地表达校准、样稿测试',
    fit: '本地化策略、文案与内容微任务',
    deliverables: ['语境地图', '本地化样稿', '审核规则'],
    evidenceExamples: '发布前后样稿、当地团队反馈、内容表现和审核记录',
    boundary: '翻译能力不自动等于市场本地化能力。',
    evidencePrompt: '补充发布样稿、互动数据或当地团队反馈',
    keywords: ['本地化', '文案', '翻译', '语言', '印尼', '泰国', '新加坡'],
  },
  {
    id: 'research',
    category: '用户研究',
    name: '海外用户研究与市场洞察',
    task: '通过研究和访谈回答进入、定位或用户需求问题',
    method: '研究设计、访谈、竞品与结论归纳',
    fit: '用户研究、市场进入与竞品分析任务',
    deliverables: ['研究方案', '脱敏纪要', '洞察与建议'],
    evidenceExamples: '研究提纲、脱敏访谈记录、分析框架和决策采纳证明',
    boundary: '小样本访谈不能直接推断总体比例。',
    evidencePrompt: '补充研究报告、脱敏纪要或决策采纳记录',
    keywords: ['研究', '访谈', '洞察', '竞品', '市场', '用户'],
  },
  {
    id: 'commerce',
    category: '电商运营',
    name: '跨境电商运营诊断',
    task: '定位选品、店铺、转化或活动运营中的增长卡点',
    method: '数据拆解、商品与页面审计、运营复盘',
    fit: '店铺诊断、选品分析与短期优化任务',
    deliverables: ['店铺诊断', '问题清单', '优化计划'],
    evidenceExamples: '店铺后台、商品页版本、运营方案和结果数据',
    boundary: '不能只展示 GMV，不说明本人动作与外部因素。',
    evidencePrompt: '补充店铺后台、运营方案与结果数据',
    keywords: ['电商', 'shopee', 'lazada', '选品', '店铺', 'gmv'],
  },
  {
    id: 'automation',
    category: 'AI 提效',
    name: '海外业务 AI 提效设计',
    task: '将重复业务流程拆成知识、规则、自动化与人工复核节点',
    method: '流程梳理、知识库、工作流编排与效果评估',
    fit: '客服、内容或运营提效微任务',
    deliverables: ['流程图', '知识结构', '工作流原型'],
    evidenceExamples: '运行流程、测试集、准确性记录、人工节省或异常复盘',
    boundary: '高风险决定必须保留人工确认和可追溯来源。',
    evidencePrompt: '补充工作流截图、运行数据或团队使用反馈',
    keywords: ['ai', '自动化', '客服', '知识库', '工作流', '提效'],
  },
  {
    id: 'creator-operations',
    category: '达人合作',
    name: '海外达人筛选与合作运营',
    task: '根据目标人群、内容质量、预算和品牌风险建立达人合作机制',
    method: '受众匹配、内容审计、互动真实性检查、报价对照和合作复盘',
    fit: '达人名单、合作 brief、投放前筛选与复盘任务',
    deliverables: ['筛选评分卡', '候选名单', 'brief 与复盘模板'],
    evidenceExamples: '候选调研、沟通记录、合作数据、内容样本和复投判断',
    boundary: '名单不等于真实关系，必须区分公开调研与已合作资源。',
    evidencePrompt: '补充候选筛选逻辑、合作记录或复投复盘',
    keywords: ['达人', 'kol', '网红', 'creator', '合作', '投放', '名单', 'brief'],
  },
  {
    id: 'growth-experiments',
    category: '增长策略',
    name: '海外增长实验与漏斗优化',
    task: '把增长目标拆成可测试假设、实验动作、指标和停止条件',
    method: '问题树、漏斗分析、实验优先级、指标设计和结果归因',
    fit: '转化、留存、投放或产品增长实验',
    deliverables: ['增长问题树', '实验队列', '指标与复盘模板'],
    evidenceExamples: '实验设计、数据口径、版本记录、结果复盘和业务采纳',
    boundary: '不能把相关性包装成因果，也不采用误导性增长手段。',
    evidencePrompt: '补充实验记录、指标口径、版本变化与复盘结论',
    keywords: ['增长', '实验', '转化', '留存', '漏斗', 'ab测试', '投放', '数据'],
  },
  {
    id: 'channel-development',
    category: '渠道拓展',
    name: '海外渠道与合作伙伴开发',
    task: '识别渠道角色、筛选潜在伙伴并完成首轮资格验证',
    method: '生态映射、候选调研、价值主张设计、触达和访谈验证',
    fit: '代理商、分销商、服务商和生态合作伙伴开发',
    deliverables: ['渠道生态图', '候选清单', '触达与筛选模板'],
    evidenceExamples: '候选清单、来源记录、沟通纪要、合作推进或失败复盘',
    boundary: '不能把公开名单描述成私人关系，也不承诺签约。',
    evidencePrompt: '补充候选来源、沟通记录和渠道验证结果',
    keywords: ['渠道', '代理商', '分销', '合作伙伴', '生态', '本地资源', '商务拓展'],
  },
  {
    id: 'b2b-generation',
    category: 'B2B 增长',
    name: '海外 B2B 线索与销售触达',
    task: '定义目标账户，研究线索并设计合规的多轮触达和资格判断',
    method: 'ICP 拆解、账户研究、信号分层、消息测试和销售反馈闭环',
    fit: 'B2B 线索研究、外贸获客、LinkedIn 或邮件触达',
    deliverables: ['目标账户清单', '触达脚本', '资格与跟进模板'],
    evidenceExamples: '名单来源、触达数据、会议转化、销售反馈和成交复盘',
    boundary: '不使用垃圾邮件、虚假身份或未经授权的数据抓取。',
    evidencePrompt: '补充名单来源、触达版本、回复或会议转化记录',
    keywords: ['b2b', '销售', '线索', '客户', 'linkedin', '邮件', '外贸', '获客'],
  },
  {
    id: 'retention-operations',
    category: '用户运营',
    name: '用户生命周期与复购运营',
    task: '识别留存节点、用户分层和流失信号，设计复购或召回动作',
    method: '队列分析、行为分层、生命周期映射、触达策略和退出规则',
    fit: 'CRM、复购、召回、会员或用户运营任务',
    deliverables: ['生命周期地图', '用户分层', '复购或召回实验'],
    evidenceExamples: '分层口径、触达方案、活动记录、留存或复购复盘',
    boundary: '不滥用个人信息，不设计骚扰式触达。',
    evidencePrompt: '补充用户分层、触达记录和留存或复购结果',
    keywords: ['用户运营', '留存', '复购', 'crm', '召回', '生命周期', '会员'],
  },
  {
    id: 'measurement',
    category: '数据分析',
    name: '业务指标与数据分析',
    task: '把业务问题转成可计算指标、分析框架和可共同使用的数据口径',
    method: '指标树、数据字典、漏斗与队列分析、异常检查和结果解释',
    fit: '增长分析、经营看板、归因口径与业务复盘',
    deliverables: ['指标字典', '分析报告', '看板或复盘模板'],
    evidenceExamples: '查询逻辑、数据字典、分析文档、看板和被采纳的业务动作',
    boundary: '不能用不完整数据给出确定结论，也不能绕过权限。',
    evidencePrompt: '补充指标定义、分析过程、数据质量检查和决策结果',
    keywords: ['数据', '分析', '指标', '看板', '漏斗', '归因', 'sql', 'bi'],
  },
  {
    id: 'delivery-management',
    category: '项目交付',
    name: '跨市场项目交付与协作',
    task: '协调总部、当地团队、供应商与渠道，控制范围、依赖和里程碑',
    method: '工作分解、RACI、风险登记、决策日志、里程碑和变更管理',
    fit: '跨市场发布、本地化项目、供应商协作和付费试用项目',
    deliverables: ['项目计划', '依赖与风险清单', '会议和验收机制'],
    evidenceExamples: '项目计划、会议纪要、交付物、风险处理和合作方评价',
    boundary: '不替代业务方决策，也不为未确认的外部依赖作保证。',
    evidencePrompt: '补充项目计划、里程碑交付、风险处理和验收记录',
    keywords: ['项目管理', '交付', '跨市场', '里程碑', '供应商', '协作', '发布'],
  },
];

export const evidenceLevels = [
  { level: 'L0', name: '初步推测', note: '来自简历或本次描述，不能替代证明' },
  { level: 'L1', name: '结构化自述', note: '案例具体，但尚无外部材料' },
  { level: 'L2', name: '材料验证', note: '作品、数据、推荐人或公开案例相互印证' },
  { level: 'L3', name: '交易验证', note: '通过平台项目获得需求方验收与评价' },
  { level: 'L4', name: '重复验证', note: '在多个任务中持续稳定交付' },
];
