import type { DiscoveryKind } from "./domain.js";
import { emptyMatchingConstraints, type MatchingConstraints, type MatchingDraft } from "./matching.js";

export const MATCHING_EXAMPLES_VERSION = "2026-09-07.2";
export type MatchingExample = { id: string; kind: DiscoveryKind; domain: "ai" | "global"; draft: MatchingDraft };
const conditions = (patch: Partial<MatchingConstraints> = {}): MatchingConstraints => ({ ...emptyMatchingConstraints(), ...patch });
const example = (id: string, kind: DiscoveryKind, domain: MatchingExample["domain"], title: string, summary: string, skills: string[], patch: Partial<MatchingDraft> = {}): MatchingExample => ({
  id: `example-${id}`, kind, domain, draft: {
    title: `${kind === "problem" ? "示例需求" : "示例人才"}｜${title}`, summary,
    skills, requiredSkills: [], workMode: "remote", engagement: "project", location: "",
    notes: "虚构示例，仅用于体验，不提供联系或真实合作。", ...patch,
  },
});

/** All content is written for product testing; no real account or profile is represented. */
export const MATCHING_EXAMPLES: readonly MatchingExample[] = [
  example("ai-rag-demand", "problem", "ai", "企业制度知识问答", "虚构场景：公司制度资料分散，希望整理知识库并建立带出处的智能问答。先对一批高频问题试点，检查引用是否正确、无答案时是否明确提示，再决定是否接入内部系统。", ["知识库", "智能问答", "RAG检索", "模型评估", "系统集成"], { requiredSkills: ["知识库", "RAG检索"], constraints: conditions({ budgetMax: 60000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 20 }) }),
  example("ai-rag-talent", "capability", "ai", "知识库与 RAG 实施", "虚构经历：本人负责制度文档清洗、分段、向量检索与引用展示，并整理问题样本检查检索和回答质量。交付可试用的知识问答、样本集及错误分析记录；系统接入范围需另行确认。", ["知识库", "智能问答", "RAG检索", "模型评估", "数据治理"], { constraints: conditions({ budgetMin: 30000, budgetMax: 60000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 24 }) }),
  example("ai-agent-demand", "problem", "ai", "销售线索整理与跟进助手", "虚构场景：销售每天手动整理线索并填写系统。希望把信息去重、分类和跟进草稿串成自动化工作流，接入现有系统；所有对外发送内容由销售确认。先交付小范围可用流程和失败处理说明。", ["流程自动化", "AI智能体", "系统集成", "测试验收"], { requiredSkills: ["系统集成"], constraints: conditions({ budgetMax: 45000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 16 }) }),
  example("ai-agent-talent", "capability", "ai", "业务自动化与 AI 助手", "虚构经历：本人用自动化工作流连接表单和客户系统，加入去重、分类、人工确认与失败重试。交付流程说明、测试用例和试点操作指南；对外发信始终保留人工确认。", ["流程自动化", "AI智能体", "系统集成", "测试验收"], { constraints: conditions({ budgetMin: 25000, budgetMax: 45000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 20 }) }),
  example("ai-evaluation-demand", "problem", "ai", "客服问答评估与改进", "虚构场景：已有客服问答原型，回答稳定性不够。需要按常见问题、无答案和越权请求构建评测样本，比较改进前后结果并提供上线建议。此次只做评估和提示词改进，不做模型微调。", ["模型评估", "提示词设计", "智能问答", "测试验收"], { requiredSkills: ["模型评估"], constraints: conditions({ budgetMax: 25000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 12 }) }),
  example("ai-evaluation-talent", "capability", "ai", "问答评测与提示词改进", "虚构经历：本人按业务问题分类建立评测样本，检查答案、出处和拒答边界，比较多版提示词并记录错误。交付评测表、复现步骤与改进建议；没有生产模型训练经历。", ["模型评估", "提示词设计", "智能问答", "测试验收"], { constraints: conditions({ budgetMin: 15000, budgetMax: 25000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 16 }) }),
  example("ai-data-demand", "problem", "ai", "AI 项目数据准备与监控", "虚构场景：已有模型服务，需要规范训练与评测数据版本，搭建错误分析看板和推理服务监控。希望先梳理数据问题并完成可复查的交付记录，数据使用范围由内部团队确认。", ["数据治理", "模型部署", "数据分析", "数据可视化"], { requiredSkills: ["数据治理"], constraints: conditions({ budgetMax: 50000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 24 }) }),
  example("ai-data-talent", "capability", "ai", "数据治理与模型服务", "虚构经历：本人负责数据清洗与版本记录，部署模型推理服务并制作错误分类看板。交付数据处理脚本、监控面板和回滚步骤；未负责底层模型训练算法。", ["数据治理", "模型部署", "数据分析", "数据可视化"], { constraints: conditions({ budgetMin: 35000, budgetMax: 50000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 28 }) }),
  example("global-market-demand", "problem", "global", "B2B 软件进入新加坡市场", "虚构场景：国内 B2B 软件准备试水新加坡，需要目标客户与竞争方案调研，访谈设计及市场进入策略。先交付可追溯的研究材料和首轮验证计划，不要求保证订单。", ["海外市场调研", "出海策略", "数据分析", "项目管理"], { requiredSkills: ["海外市场调研"], constraints: conditions({ markets: ["新加坡"], languages: ["英语"], budgetMax: 40000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 12 }) }),
  example("global-market-talent", "capability", "global", "新加坡 B2B 市场研究", "虚构经历：本人围绕新加坡企业软件客户整理竞品与渠道资料，设计英语访谈提纲，输出客户分层及进入路径。交付研究来源表、访谈纪要与试点建议；没有承诺销售转化。", ["海外市场调研", "出海策略", "数据分析", "项目管理"], { constraints: conditions({ markets: ["新加坡"], languages: ["英语", "中文"], budgetMin: 20000, budgetMax: 40000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 18 }) }),
  example("global-growth-demand", "problem", "global", "美国独立站获客试点", "虚构场景：消费品品牌已有英语独立站，希望面向美国客户开展广告投放与 SEO 优化，分析从访问到询盘的转化。先验证一条获客路径，分别记录服务费与媒体预算。", ["海外获客", "广告投放", "SEO优化", "数据分析"], { requiredSkills: ["广告投放"], constraints: conditions({ markets: ["美国"], languages: ["英语"], budgetMax: 18000, budgetCurrency: "CNY", budgetPeriod: "month", weeklyHours: 12 }) }),
  example("global-growth-talent", "capability", "global", "美国市场投放与转化分析", "虚构经历：本人为英语独立站整理关键词、设置广告与转化追踪，检查落地页问题并输出每周分析。交付投放结构、数据看板与复盘；报价仅为服务费，媒体费用需单独确认。", ["海外获客", "广告投放", "SEO优化", "数据分析"], { constraints: conditions({ markets: ["美国"], languages: ["英语"], budgetMin: 12000, budgetMax: 18000, budgetCurrency: "CNY", budgetPeriod: "month", weeklyHours: 16 }) }),
  example("global-localization-demand", "problem", "global", "日本市场产品内容本地化", "虚构场景：软件产品准备进入日本，需要梳理网站与帮助中心内容，并完成日语内容本地化和客服支持流程。以首批关键页面、术语表和常见问题说明作为阶段交付。", ["内容本地化", "内容创作", "客户服务"], { requiredSkills: ["内容本地化"], constraints: conditions({ markets: ["日本"], languages: ["日语"], budgetMax: 30000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 15 }) }),
  example("global-localization-talent", "capability", "global", "日语产品本地化", "虚构经历：本人整理软件界面与帮助中心术语，完成日语内容本地化、编辑校对和客服常见问题分类。交付双语术语表、页面文稿与质量检查记录；未承担日本当地法律审查。", ["内容本地化", "内容创作", "客户服务"], { constraints: conditions({ markets: ["日本"], languages: ["日语", "中文"], budgetMin: 18000, budgetMax: 30000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 20 }) }),
  example("global-channel-demand", "problem", "global", "德国渠道伙伴筛选", "虚构场景：工业设备企业计划拓展德国市场，需要梳理潜在渠道伙伴、整理筛选标准并协调首轮沟通。先交付伙伴研究和跟进计划；产品认证及法律事项由专门机构确认。", ["渠道拓展", "海外市场调研", "跨境运营", "项目管理"], { requiredSkills: ["渠道拓展"], constraints: conditions({ markets: ["德国"], languages: ["英语"], budgetMax: 45000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 16 }) }),
  example("global-channel-talent", "capability", "global", "德国 B2B 渠道协作", "虚构经历：本人研究德国行业渠道、整理伙伴筛选表、安排英语沟通并跟进样品和交付节点。交付渠道研究、沟通纪要与行动计划；不代表对合作方信誉或产品合规作出认证。", ["渠道拓展", "海外市场调研", "跨境运营", "项目管理"], { constraints: conditions({ markets: ["德国"], languages: ["英语", "德语"], budgetMin: 30000, budgetMax: 45000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 20 }) }),
  example("global-b2b-part-time-demand", "problem", "global", "德国工业客户开发 · 兼职", "虚构场景：工业传感器企业准备开拓德国市场，需要市场调研、客户画像和 B2B 线索开发。通过 LinkedIn 筛选潜在线索并记录到 CRM，先验收有效客户名单与意向访谈，不要求保证成交。", ["海外市场调研", "海外获客"], { engagement: "part_time", requiredSkills: ["海外市场调研"], constraints: conditions({ markets: ["德国"], languages: ["英语"], budgetMax: 18000, budgetCurrency: "CNY", budgetPeriod: "month", weeklyHours: 12 }) }),
  example("global-b2b-part-time-talent", "capability", "global", "德国 B2B 线索研究 · 兼职", "虚构经历：本人负责德国工业产品市场调研、竞争产品分析与客户画像，通过 LinkedIn 筛选潜在线索并记录到 CRM。交付调研表、筛选依据和跟进记录；后续签约由销售团队负责。", ["海外市场调研", "海外获客"], { engagement: "part_time", constraints: conditions({ markets: ["德国"], languages: ["英语"], budgetMin: 10000, budgetMax: 18000, budgetCurrency: "CNY", budgetPeriod: "month", weeklyHours: 20 }) }),
  example("global-us-content-demand", "problem", "global", "美国品牌英语内容本地化", "虚构场景：面向美国消费者的独立站需要英语产品页重写、SEO 关键词研究和术语整理。按项目交付可审核的英文页面、关键词清单和前后对照稿；本阶段不做广告投放。", ["内容本地化", "内容创作", "SEO优化"], { requiredSkills: ["内容本地化"], constraints: conditions({ markets: ["美国"], languages: ["英语"], budgetMax: 28000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 10 }) }),
  example("global-us-content-talent", "capability", "global", "美国市场英语文案与 SEO", "虚构经历：本人为面向美国的品牌重写英语产品页，研究 SEO 关键词和搜索意图，并与设计师校对术语。交付页面文稿、关键词表和审校记录；未负责广告投放，也不以团队流量成果代替个人贡献。", ["内容本地化", "内容创作", "SEO优化"], { constraints: conditions({ markets: ["美国"], languages: ["英语"], budgetMin: 15000, budgetMax: 28000, budgetCurrency: "CNY", budgetPeriod: "project", weeklyHours: 18 }) }),
  example("ai-n8n-part-time-demand", "problem", "ai", "n8n 与 CRM 流程维护 · 兼职", "虚构场景：销售团队需要持续维护 n8n 表单汇总与 CRM 接口，加入去重、人工审批和失败重试。先让记录正确入库并可复查；对外发信保留人工控制，按兼职方式协作。", ["流程自动化", "系统集成", "测试验收"], { engagement: "part_time", requiredSkills: ["系统集成"], constraints: conditions({ budgetMax: 16000, budgetCurrency: "CNY", budgetPeriod: "month", weeklyHours: 12 }) }),
  example("ai-n8n-part-time-talent", "capability", "ai", "n8n 自动化与系统接口 · 兼职", "虚构经历：本人负责 n8n 工作流与 CRM 接口，接入表单，加入去重、人工审批和失败重试。交付流程图、测试记录和维护说明；每周可投入 20 小时，接受远程兼职。", ["流程自动化", "系统集成", "测试验收"], { engagement: "part_time", constraints: conditions({ budgetMin: 10000, budgetMax: 16000, budgetCurrency: "CNY", budgetPeriod: "month", weeklyHours: 20 }) }),
];
